name: "Setup SSH"
description: "Setup SSH key from secrets and configure SSH for remote command execution."
author: "Anggit Herdianto"
inputs:
    host:
        description: "SSH host address or IP to connect to."
    port:
        description: "SSH port number for the connection."
        default: "22"
    id_ecdsa:
        description: "SSH private ECDSA key content for authentication."
    id_ecdsa_pub:
        description: "SSH public ECDSA key content for authentication."
    id_ed25519:
        description: "SSH private Ed25519 key content for authentication."
    id_ed25519_pub:
        description: "SSH public Ed25519 key content for authentication."
    id_rsa:
        description: "SSH private RSA key content for authentication."
    id_rsa_pub:
        description: "SSH public RSA key content for authentication."

outputs:
    stdout:
        description: "Standard output of the executed commands when capture_stdout is enabled."
        value: ${{ steps.entrypoint.outputs.stdout }}

runs:
    using: "composite"
    steps:
        -
            name: Setup SSH
            shell: bash
            env:
                INPUT_HOST: ${{ inputs.host }}
                INPUT_PORT: ${{ inputs.port || '22' }}
                INPUT_ID_ECDSA: ${{ inputs.id_ecdsa || '' }}
                INPUT_ID_ECDSA_PUB: ${{ inputs.id_ecdsa_pub || '' }}
                INPUT_ID_ED25519: ${{ inputs.id_ed25519 || '' }}
                INPUT_ID_ED25519_PUB: ${{ inputs.id_ed25519_pub || '' }}
                INPUT_ID_RSA: ${{ inputs.id_rsa || '' }}
                INPUT_ID_RSA_PUB: ${{ inputs.id_rsa_pub || '' }}
            run: |
                mkdir -p ~/.ssh

                [ -n "${INPUT_ID_ECDSA}" ]       && echo "${INPUT_ID_ECDSA}" > ~/.ssh/id_ecdsa
                [ -n "${INPUT_ID_ECDSA_PUB}" ]   && echo "${INPUT_ID_ECDSA_PUB}" > ~/.ssh/id_ecdsa.pub

                [ -n "${INPUT_ID_ED25519}" ]     && echo "${INPUT_ID_ED25519}" > ~/.ssh/id_ed25519
                [ -n "${INPUT_ID_ED25519_PUB}" ] && echo "${INPUT_ID_ED25519_PUB}" > ~/.ssh/id_ed25519.pub

                [ -n "${INPUT_ID_RSA}" ]         && echo "${INPUT_ID_RSA}" > ~/.ssh/id_rsa
                [ -n "${INPUT_ID_RSA_PUB}" ]     && echo "${INPUT_ID_RSA_PUB}" > ~/.ssh/id_rsa.pub

                chmod 644 ~/.ssh
                chmod 600 ~/.ssh/*

                ssh-keyscan -p "${INPUT_PORT}" "${INPUT_HOST}" > ~/.ssh/known_hosts

branding:
    icon: "terminal"
    color: "gray-dark"
